services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: on-failure:5
    ports:
    - 2660:5050
    volumes:
    - /volume1/docker/stacks/postgresql/pgadmin:/var/lib/pgadmin:rw
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5050
    mem_limit: 256m
    cpu_shares: 768
    user: 0:0
  db:
    image: postgres
    container_name: PostgreSQL
    restart: on-failure:5
    ports:
    - 2665:5454
    volumes:
    - /volume1/docker/stacks/postgresql:/var/lib/postgresql:rw
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: thunder_db
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -q
      - -d
      - thunder_db
      - -U
      - root
    mem_limit: 256m
    cpu_shares: 768
