#!/usr/bin/env bash
# scripts/deploy-portainer.sh
# Deploy Portainer stack on Synology NAS
# Generates .env file on the fly and deploys via Container Manager or CLI

set -euo pipefail

STACK_NAME="portainer"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STACK_DIR="$ROOT_DIR/$STACK_NAME"
NAS_USER="isaac"

# Default values (can be overridden by environment variables)
TS_TAILNET_DOMAIN="${TS_TAILNET_DOMAIN:-tail303fda.ts.net}"
TS_HOSTNAME="${TS_HOSTNAME:-portainer}"
ADMIN_EMAIL="${ADMIN_EMAIL:-isaac@kehle.org}"
TZ="${TZ:-America/New_York}"
NAS_LAN_IP="${NAS_LAN_IP:-192.168.68.50}"

usage() {
  cat >&2 <<EOF
Usage: scripts/deploy-portainer.sh <command> <ssh-host>

Commands:
  env     <ssh-host>    Generate and display .env file content
  dirs    <ssh-host>    mkdir -p + chown the stack's directories on the NAS
  push    <ssh-host>    scp compose.yaml + generate .env to NAS
  up      <ssh-host>    docker compose up -d on NAS (if docker available)
  all     <ssh-host>    env + dirs + push + up

Environment Variables:
  TS_TAILNET_DOMAIN    Tailscale domain (default: tail303fda.ts.net)
  TS_HOSTNAME          Portainer hostname (default: portainer)
  ADMIN_EMAIL          Admin email for Portainer (default: isaac@kehle.org)
  TZ                   Timezone (default: America/New_York)
  NAS_LAN_IP           NAS LAN IP (default: 192.168.68.50)
  TS_AUTHKEY           Tailscale auth key (REQUIRED, prompt if not set)

Examples:
  # Generate .env content
  scripts/deploy-portainer.sh env voyager

  # Deploy via Container Manager UI (recommended)
  scripts/deploy-portainer.sh push voyager
  # Then manually deploy in Container Manager UI

  # Deploy via CLI (if docker available)
  scripts/deploy-portainer.sh all voyager

  # Full deployment with custom values
  TS_AUTHKEY=tskey-auth-xxx scripts/deploy-portainer.sh all voyager
EOF
}

generate_env() {
  # Prompt for TS_AUTHKEY if not set
  if [[ -z "${TS_AUTHKEY:-}" ]]; then
    echo "⚠️  TS_AUTHKEY not set. Please provide Tailscale auth key:"
    read -sp "TS_AUTHKEY=" TS_AUTHKEY
    echo
    if [[ -z "$TS_AUTHKEY" ]]; then
      echo "❌ TS_AUTHKEY is required. Exiting."
      exit 1
    fi
  fi

  cat <<EOF
# Portainer Stack Environment
# Generated by deploy-portainer.sh on $(date)

# Tailscale Configuration
TS_TAILNET_DOMAIN=$TS_TAILNET_DOMAIN
TS_HOSTNAME=$TS_HOSTNAME
TS_CERT_DOMAIN=${TS_HOSTNAME}.${TS_TAILNET_DOMAIN}
TS_AUTHKEY=$TS_AUTHKEY

# System Configuration
TZ=$TZ
ADMIN_EMAIL=$ADMIN_EMAIL
NAS_LAN_IP=$NAS_LAN_IP
EOF
}

cmd_env() {
  local ssh_host="$1"
  echo "=== Generated .env file ==="
  generate_env
  echo "=========================="
  echo ""
  echo "SSH Host: $ssh_host"
  echo "Environment variables:"
  echo "  TS_TAILNET_DOMAIN: $TS_TAILNET_DOMAIN"
  echo "  TS_HOSTNAME: $TS_HOSTNAME"
  echo "  ADMIN_EMAIL: $ADMIN_EMAIL"
  echo "  TZ: $TZ"
  echo "  NAS_LAN_IP: $NAS_LAN_IP"
  echo "  TS_AUTHKEY: [REDACTED]"
}

cmd_dirs() {
  local ssh_host="$1"
  echo "Creating stack directories on $ssh_host..."
  
  # Create secure secrets directory
  ssh "$ssh_host" "sudo mkdir -p /volume1/docker/portainer-secrets/{certs,chisel}"
  ssh "$ssh_host" "sudo chmod 700 /volume1/docker/portainer-secrets"
  ssh "$ssh_host" "sudo chown root:root /volume1/docker/portainer-secrets"
  
  # Create stacks directory
  ssh "$ssh_host" "mkdir -p /volume1/docker/stacks/$STACK_NAME"
  
  echo "Done."
}

cmd_push() {
  local ssh_host="$1"
  echo "Pushing stack files to $ssh_host..."
  
  # Copy compose.yaml
  scp "$STACK_DIR/old/compose.yaml" "$ssh_host:/volume1/docker/stacks/$STACK_NAME/docker-compose.yml"
  
  # Generate and push .env file
  echo "Generating .env file..."
  local env_content
  env_content=$(generate_env)
  echo "$env_content" | ssh "$ssh_host" "cat > /volume1/docker/stacks/$STACK_NAME/.env"
  
  # Set secure permissions on .env
  ssh "$ssh_host" "sudo chmod 600 /volume1/docker/stacks/$STACK_NAME/.env"
  ssh "$ssh_host" "sudo chown root:root /volume1/docker/stacks/$STACK_NAME/.env"
  
  echo "Done."
  echo ""
  echo "=== Next Steps ==="
  echo "1. Open Container Manager → Project tab"
  echo "2. Create → Project → Import from YAML/JSON"
  echo "3. Paste content from: /volume1/docker/stacks/$STACK_NAME/docker-compose.yml"
  echo "4. Select .env file: /volume1/docker/stacks/$STACK_NAME/.env"
  echo "5. Deploy"
}

cmd_up() {
  local ssh_host="$1"
  echo "Attempting to deploy stack on $ssh_host..."
  
  # Try docker compose (may not work on Synology)
  if ssh "$ssh_host" "sudo /var/packages/ContainerManager/target/tool/docker compose version 2>&1" | grep -q "Docker Compose"; then
    ssh "$ssh_host" "cd /volume1/docker/stacks/$STACK_NAME && sudo /var/packages/ContainerManager/target/tool/docker compose up -d"
    echo "Deployed via CLI."
  else
    echo "⚠️  Docker CLI not available on Synology."
    echo "Please deploy via Container Manager UI instead."
    echo "See cmd_push output for instructions."
  fi
}

cmd_all() {
  local ssh_host="$1"
  echo "=== Full Deployment ==="
  echo ""
  
  # Generate env (will prompt for TS_AUTHKEY if needed)
  echo "1. Generating .env..."
  cmd_env "$ssh_host"
  echo ""
  
  # Create directories
  echo "2. Creating directories..."
  cmd_dirs "$ssh_host"
  echo ""
  
  # Push files
  echo "3. Pushing files..."
  cmd_push "$ssh_host"
  echo ""
  
  # Try to deploy via CLI
  echo "4. Attempting CLI deployment..."
  cmd_up "$ssh_host"
  echo ""
  
  echo "=== Complete ==="
  echo ""
  echo "Portainer will be available at:"
  echo "  http://${NAS_LAN_IP}:9000"
  echo "  http://${TS_HOSTNAME}.${TS_TAILNET_DOMAIN}:9000"
  echo ""
  echo "To deploy via Container Manager UI:"
  echo "  1. Open DSM → Container Manager → Project tab"
  echo "  2. Create → Project → Import from YAML/JSON"
  echo "  3. Paste content from: /volume1/docker/stacks/$STACK_NAME/docker-compose.yml"
  echo "  4. Select .env file: /volume1/docker/stacks/$STACK_NAME/.env"
  echo "  5. Deploy"
}

# Main
case "${1:-}" in
  env)    cmd_env "$2" ;;
  dirs)   cmd_dirs "$2" ;;
  push)   cmd_push "$2" ;;
  up)     cmd_up "$2" ;;
  all)    cmd_all "$2" ;;
  *)      usage ;;
esac
