#!/usr/bin/env bash
# scripts/gen-env.sh — generate <stack>/env.txt and render any <stack>/*.tmpl
# files from the central secrets file.
#
# Secrets (Tailscale auth keys, passwords, API keys, ...) live in a single
# file outside this repo — see iac-secrets.env.example for the format and
# scripts/lib.sh for the default path (IAC_SECRETS_FILE). This script never
# touches that file; it only reads it.
#
# Usage:
#   scripts/gen-env.sh <stack>          # generate ./<stack>/env.txt + render templates
#   scripts/gen-env.sh --all            # do the above for every stack
#
# Generated/rendered output (env.txt, and any *.tmpl -> stripped-suffix file)
# is gitignored and safe to scp to the NAS as-is.
#
# Why env.txt and not .env: docker compose still needs a literal .env file
# to auto-load (scripts/deploy.sh's `up` step passes --env-file explicitly,
# so that's covered) — but Portainer's "Load variables from .env file"
# button opens a normal OS file picker, and dotfiles are hidden by default
# in most of those (e.g. Finder's Open dialog). A visible, selectable
# filename matters more here than matching docker compose's default name.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib.sh
source "$ROOT_DIR/scripts/lib.sh"

usage() {
  echo "Usage: $0 <stack> | --all" >&2
  exit 1
}

gen_one() {
  local stack="$1"
  require_stack "$stack"

  if [[ ! -f "$IAC_SECRETS_FILE" ]]; then
    echo "ERROR: secrets file not found at $IAC_SECRETS_FILE" >&2
    echo "Copy iac-secrets.env.example there and fill in real values first." >&2
    exit 1
  fi

  render_templates "$stack"

  local example="$stack/.env.example"
  if [[ ! -f "$example" ]]; then
    echo "==> $stack: no .env.example, nothing to generate"
    return 0
  fi

  local out="$stack/env.txt"
  {
    echo "# Generated by scripts/gen-env.sh from $IAC_SECRETS_FILE"
    echo "# Do not edit by hand — edit the secrets file and regenerate instead."
    echo "# Regenerate with: scripts/gen-env.sh $stack"
  } >"$out"

  local missing=()
  while IFS= read -r line || [[ -n "$line" ]]; do
    # skip blank lines and comments
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^[[:space:]]*$ ]] && continue
    [[ "$line" == *"="* ]] || continue

    local key="${line%%=*}"
    local default_val="${line#*=}"
    local value=""

    value="$(get_secret_value "$key")"

    # TS_AUTHKEY resolution: stack-specific TS_AUTHKEY_<STACK> in the
    # secrets file wins if set; otherwise fall back to the global
    # TS_AUTHKEY (most stacks share one reusable key).
    if [[ "$key" == "TS_AUTHKEY" ]]; then
      local stack_key
      stack_key="$(get_secret_value "TS_AUTHKEY_$(echo "$stack" | tr '[:lower:]' '[:upper:]')")"
      [[ -n "$stack_key" ]] && value="$stack_key"
    fi

    if [[ -z "$value" && "$key" == "TS_CERT_DOMAIN" ]]; then
      local tailnet
      tailnet="$(get_secret_value "TS_TAILNET_DOMAIN")"
      [[ -n "$tailnet" ]] && value="${stack}.${tailnet}"
    fi

    if [[ -z "$value" ]]; then
      value="$default_val"
    fi

    # .env.example defaults may reference ${TS_TAILNET_DOMAIN} (e.g.
    # TS_CERT_DOMAIN=nextcloud.${TS_TAILNET_DOMAIN}) — expand it from the
    # secrets file here, so the placeholder never leaks into a real .env.
    if [[ "$value" == *'${TS_TAILNET_DOMAIN}'* ]]; then
      local tailnet
      tailnet="$(get_secret_value "TS_TAILNET_DOMAIN")"
      if [[ -n "$tailnet" ]]; then
        value="${value//'${TS_TAILNET_DOMAIN}'/$tailnet}"
      fi
    fi

    echo "${key}=${value}" >>"$out"

    case "$value" in
      ""|*changeme*|*CHANGE_ME*|tskey-auth-xxxx*|tskey-...|*'${TS_TAILNET_DOMAIN}'*|*xxxxxxxx*)
        missing+=("$key")
        ;;
    esac
  done <"$example"

  echo "==> $stack: wrote $out"
  if [[ "${#missing[@]}" -gt 0 ]]; then
    echo "    ⚠ still unset/placeholder: ${missing[*]}"
    echo "    add these to $IAC_SECRETS_FILE and re-run"
  fi
}

[[ $# -eq 1 ]] || usage

cd "$ROOT_DIR"

if [[ "$1" == "--all" ]]; then
  for s in "${ALL_STACKS[@]}"; do
    gen_one "$s"
  done
else
  gen_one "$1"
fi
