services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - 8384:8384
    - 22000:22000/tcp
    - 22000:22000/udp
    - 21027:21027/udp
    volumes:
    - /volume1/docker/stacks/syncthing/config:/config:rw
    - /volume1/docker/stacks/syncthing/sync:/var/syncthing/sync:rw
    - /volume1/docker/stacks/syncthing/data:/var/syncthing/data:rw
    environment:
    - TZ=${TZ}
    - PUID=${SYNC_PUID}
    - PGID=${SYNC_PGID}
    healthcheck:
      test: curl -f http://localhost:8384/ || exit 1
    hostname: synology-nas
  ts-syncthing:
    image: tailscale/tailscale:latest
    container_name: ts-syncthing
    restart: unless-stopped
    depends_on:
    - syncthing
    network_mode: service:syncthing
    volumes:
    - /volume1/docker/stacks/syncthing/ts-config:/config
    - /volume1/docker/stacks/syncthing/ts-state:/var/lib/tailscale
    environment:
    - TS_HOSTNAME=syncthing
    - TS_AUTHKEY=${TS_AUTHKEY}
    - TS_STATE_DIR=/var/lib/tailscale
    - TS_AUTH_ONCE=true
    - TS_SERVE_CONFIG=/config/serve.json
    cap_add:
    - NET_ADMIN
    - NET_RAW
    devices:
    - /dev/net/tun:/dev/net/tun
